import type { Metadata } from "next";
import { Nunito, Creepster } from "next/font/google";
import "./globals.css";
import "../styles/main.scss";

import ThemeProvider from "./ThemeProvider";
import NProgressProvider from "@/components/common/NProgressProvider";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";
import MainContent from "./MainContent";
import { AppProvider } from "@/context/AppContext";
import SplashCursor from "@/components/ui/SplashCursor";

const nunito = Nunito({
  variable: "--font-nunito",
  weight: ["400", "600", "900", "1000"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

const creepster = Creepster({
  variable: "--font-creepster",
  weight: ["400"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "NURUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${creepster.variable} antialiased bg-[var(--background-color)] flex flex-col min-h-screen font-nunito`}
      >
        <AppProvider>
          <ThemeProvider>
            <NProgressProvider />
            <SplashCursor />
            <Navbar />
            <MainContent>{children}</MainContent>
            <Footer />
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
