import type { Metadata } from "next";
import { Nunito, Creepster } from "next/font/google";
import "./globals.css";
import "../styles/main.scss";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Provider from "./Provider";
import NProgressProvider from "@/components/common/NProgressProvider";
import "react-tabs/style/react-tabs.css";

const nunito = Nunito({
  variable: "--font-nunito",
  weight: ["400", "600", "900", "1000"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

const creepster = Creepster({
  variable: "--font-creepster",
  weight: ["400"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${creepster.variable} antialiased bg-[var(--background-color)] flex flex-col min-h-screen font-nunito`}
      >
        <Provider>
          <NProgressProvider />
          <Navbar />
          <div className="pb-24">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
